### ISSUE TITLE
License file in npm package v1.0.0

### ISSUE THREAD

**Issue by dariagrudzien** [sindresorhus/is-path-cwd#5]
@sindresorhus Hi Sindre, thank you for this package. Would you mind adding the license file to the npm package of v1.0.0? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Additionally I noticed the license file does not include the date, which makes it invalid. I'd greatly appreciate it if you could add the dates to the license files in GH repo as well.

Many thanks for your consideration.

**Comment by sindresorhus** [comment]
npm used to have a bug where it didn't include a licence file. That's why it's missing. Unfortunately, I don't have time or interest to update old versions. Just use the latest version which correctly includes the license file.

> Additionally I noticed the license file does not include the date, which makes it invalid.

The year is not required.
